#!/usr/bin/perl -w
#program to find highness membership functions of a crisp set
@marks = qw(1 4 5 7 2); #marks of students in the exam
$g = 10; #maximum marks
$n = @marks;
$h = $g/2;
print "The maximum marks for the exam are $g \n";
print "The total number of students appeared for the test are $n \n";
print "The individual marks of students are @marks \n";
for ($i = 0;$i < $n;$i++)
  {
   if ( $marks[$i] <= $h )
    {
     $mem_high[$i] = '0';
    }
     elsif ( $marks[$i] > $h )
         { 
          $mem_high[$i] = $marks[$i]/$h-1;
          }
    }
     print "The highness membership functions of the students are : @mem_high \n ";
$sum = 0;
foreach (@mem_high)
      {
	  $deg_high += $_;
      }
      print "The degree of highness is : $deg_high \n";
